### ISSUE TITLE
Intro writing effect does not keep static text and lacks erase-out animation

### ISSUE THREAD

**Issue by pcorreia-it** [pcorreia-it/journal#4]
### Bug Description
The current writing effect on the intro renders the whole string (e.g., "Paulo é pai") immediately, then starts the typing effect and proceeds to the erasing effect. This is not the expected behavior.

### Expected Behavior
- The text "Paulo " should remain visible on the screen at all times.
- The remaining words should be typed in, then erased out, in an infinite loop.

### Actual Behavior
- The effect currently renders the entire string at first, then begins the typing effect, followed by the erasing effect.
- It does not keep a word (e.g., "Paulo ") on the screen while animating the rest.
- The erasing effect is not present.

### Steps to Reproduce
1. View the intro writing effect.
2. Observe that the full string appears instantly, then types and erases the rest.

### Code Snippets
**HTML**
```html
<p id="phrase">
  Moonlight is just the sun in pajamas
</p>
```

**CSS**
```css
@import url('https://fonts.googleapis.com/css2?family=Syne+Mono&display=swap');

body {
  display: flex;
  width: 100%;
  height: 100vh;
  justify-content: center;
  align-items: center;
  background-image: radial-gradient(#946262, #884949);
  margin: 0;
  overflow: hidden;
}

p {
  display: flex;
  font-size: 4.5cqw;
  font-family: Syne Mono;
  position: relative;
  color: #f5f5f5;
  
  &::after {
    content: "|";
    animation: blinking 0.9s step-end infinite;
    position: absolute;
    left: 100%;
  }
}

span {
    overflow: hidden;
    height: fit-content;
    white-space: nowrap;
}

button {
  font-size: 4.5cqw;
  font-family: Syne Mono;
  outline: none;
  border: none;
  appearence: none;
  background: none;
  text-decoration: underline;
  color: #f5f5f5;
  cursor: pointer;
  position: absolute;
  bottom: 3%;
  opacity: 0.6;

  &:hover {
    opacity: 1;
  }
}

@keyframes blinking {
  50% { color: transparent; }
}

@keyframes typing {
  from { width: 0; }
}
```

**JS**
```js
const ANIMATION_TIME_MS = 3600

const start = async () => {
  const text = phrase.textContent.trim()
  const charactersQuantity = text.length
  
  phrase.innerHTML = `<span id="span">${text}</span>`
  span.style.width = charactersQuantity + "ch"
  span.style.animation = `typing ${ANIMATION_TIME_MS}ms steps(${charactersQuantity})`
}

start()

// ---- reset section

const TEXTS = [
  "Moonlight is just the sun in pajamas",
  "Stars are just sky freckles",
  "Socks are sweaters for feet",
  "Snow is sky confetti",
  "Dreams are brain cartoons",
  "Popcorn is corn surprised",
  "Fog is just cloud cosplay",
  "Sunsets are sky yawns",
  "Bubbles are air in costume",
  "Bananas are fruit in pajamas",
  "Echoes are sound’s boomerangs",
  "Leaves are trees changing outfits",
  "Alarm clocks are regret machines",
  "Balloons are air wearing jackets",
  "Thunder is the clouds arguing"
]

let currentTextIndex = 0

const reset = () => {
  if(currentTextIndex >= TEXTS.length - 1) currentTextIndex = 0
  else currentTextIndex++

  phrase.innerHTML = `<span id="span">${TEXTS[currentTextIndex]}</span>`
  span.style.width = TEXTS[currentTextIndex].length + "ch"
  span.style.animation = `typing ${ANIMATION_TIME_MS}ms steps(${TEXTS[currentTextIndex].length})`
}
```

### Additional Notes
- These snippets do not have the erase-out effect or keep a static word on the screen.
- Assigning to @pcorreia-it.
